Repository 2055Java-Nick/Rev-Connect-API, pull requests merged in 2024-08, with the labels that each got.

#20 Feature/#17 auth layer
  .gitignore
  .vscode/settings.json
  README.md
  pom.xml
  src/main/java/com/rev_connect_api/RevConnectApiApplication.java
  src/main/java/com/rev_connect_api/config/AppConfig.java
  src/main/java/com/rev_connect_api/config/SecurityConfig.java
  src/main/java/com/rev_connect_api/controllers/AuthController.java
  src/main/java/com/rev_connect_api/controllers/HomeController.java
  src/main/java/com/rev_connect_api/controllers/UserController.java
  src/main/java/com/rev_connect_api/dto/LoginRequestDTO.java
  src/main/java/com/rev_connect_api/dto/UserRegistrationDTO.java
  src/main/java/com/rev_connect_api/dto/UserResponseDTO.java
  src/main/java/com/rev_connect_api/dto/UserUpdateDTO.java
  src/main/java/com/rev_connect_api/mapper/UserMapper.java
  src/main/java/com/rev_connect_api/models/Role.java
  src/main/java/com/rev_connect_api/models/User.java
  src/main/java/com/rev_connect_api/repositories/UserRepository.java
  src/main/java/com/rev_connect_api/security/JWTAuthenticationFilter.java
  src/main/java/com/rev_connect_api/security/JwtUtil.java
  src/main/java/com/rev_connect_api/services/AuthService.java
  src/main/java/com/rev_connect_api/services/UserService.java
  src/main/resources/application.properties
  src/main/resources/data.sql
  src/test/java/com/rev_connect_api/CommentsTest.java
  src/test/java/com/rev_connect_api/LikesTest.java
  src/test/java/com/rev_connect_api/SharesTest.java
  src/test/java/com/rev_connect_api/mapper/UserMapperTest.java
  src/test/java/com/rev_connect_api/security/AuthControllerTest.java
  src/test/java/com/rev_connect_api/security/JwtUtilTest.java
Labels: enhancement, help wanted

#39 hotfix/fix post controller
  pom.xml
  src/main/java/com/rev_connect_api/config/SecurityConfig.java
  src/main/java/com/rev_connect_api/controllers/PostController.java
  src/main/java/com/rev_connect_api/dto/PostRequestDTO.java
  src/main/java/com/rev_connect_api/dto/PostResponseDTO.java
  src/main/java/com/rev_connect_api/mapper/PostMapper.java
  src/main/java/com/rev_connect_api/models/Media.java
  src/main/java/com/rev_connect_api/models/Post.java
  src/main/java/com/rev_connect_api/repositories/MediaRepository.java
  src/main/java/com/rev_connect_api/repositories/PostRepository.java
  src/main/java/com/rev_connect_api/services/MediaService.java
  src/main/java/com/rev_connect_api/services/PostService.java
  src/main/java/com/rev_connect_api/utils/TimestampUtil.java
  src/main/resources/data.sql
  src/test/java/com/rev_connect_api/mapper/PostMapperTest.java
  src/test/java/com/rev_connect_api/posts/PostControllerTest.java
Labels: enhancement

#44 Bugfix/remove failing tests
  src/test/java/com/rev_connect_api/CommentsTest.java
  src/test/java/com/rev_connect_api/LikesTest.java
  src/test/java/com/rev_connect_api/SharesTest.java
Labels: bug

#46 Hotfix/Fix user controller
  src/main/java/com/rev_connect_api/controllers/UserController.java
  src/main/java/com/rev_connect_api/dto/UserRegistrationDTO.java
  src/main/java/com/rev_connect_api/dto/UserUpdateDTO.java
  src/main/java/com/rev_connect_api/mapper/UserMapper.java
  src/main/java/com/rev_connect_api/services/UserService.java
  src/test/java/com/rev_connect_api/mapper/UserMapperTest.java
Labels: bug

#23 Feature/#6 as a business user i should be able to register myself and create an account
  .mvn/wrapper/maven-wrapper.properties
  pom.xml
  src/test/java/com/rev_connect_api/UserApiTests.java
  src/test/java/com/rev_connect_api/UserControllerIntegrationTests.java
  src/test/java/com/rev_connect_api/UserTests.java
Labels: documentation, enhancement

#53 feature/fifunmitimothy tags taggedusers
  src/main/java/com/rev_connect_api/controllers/PostController.java
  src/main/java/com/rev_connect_api/dto/PostRequestDTO.java
  src/main/java/com/rev_connect_api/dto/PostResponseDTO.java
  src/main/java/com/rev_connect_api/dto/TagDTO.java
  src/main/java/com/rev_connect_api/mapper/PostMapper.java
  src/main/java/com/rev_connect_api/mapper/TagMapper.java
  src/main/java/com/rev_connect_api/models/Post.java
  src/main/java/com/rev_connect_api/models/Tag.java
  src/main/java/com/rev_connect_api/repositories/TagRepository.java
  src/main/java/com/rev_connect_api/services/PostService.java
  src/main/java/com/rev_connect_api/services/TagService.java
  src/main/resources/data.sql
  src/test/java/com/rev_connect_api/mapper/PostMapperTest.java
  src/test/java/com/rev_connect_api/mapper/TagMapperTest.java
  src/test/java/com/rev_connect_api/posts/PostControllerTest.java
  src/test/java/com/rev_connect_api/services/TagServiceTest.java
Labels: enhancement

#55 feature/#54 update localDateTime format
  src/main/java/com/rev_connect_api/dto/PostResponseDTO.java
  src/main/java/com/rev_connect_api/dto/UserRegistrationDTO.java
Labels: enhancement
